<?php


namespace App\Http\Request\Back;


use Illuminate\Foundation\Http\FormRequest;

class SettingUpdateRequest extends FormRequest
{
    public function authorize(){
        return true;
    }

    public function rules(){
        return [
            'name'=>'required|max:20',
            'description'=>'max:50',
            'primaryEmail'=>'email',
            'secondaryEmail'=>'email',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
