<?php


namespace Modules\CMS\Http\Requests\Back;


use Illuminate\Foundation\Http\FormRequest;

class SliderStoreRequest extends FormRequest
{
    public function authorize(){
        return true;
    }

    public function rules(){
        return [
            'heading'=>'max:50',
            'subHeading'=>'max:70',
            'text'=>'max:500',
            'btnLink'=>'requiredIf:hasButton,on',
            'btnText'=>'requiredIF:hasButton,on'
        ];
    }
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
